name: Get SHA1

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  sha1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Download Gradle Wrapper JAR if missing
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            mkdir -p gradle/wrapper
            curl -L https://raw.githubusercontent.com/gradle/gradle/v8.0.0/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
          fi

      - name: Get SHA1 Fingerprint
        run: ./gradlew signingReport || true
